# Generated by Django 4.2.7 on 2023-11-16 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expireson', models.DateTimeField()),
                ('sp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generalname', models.CharField(max_length=30)),
                ('specificname', models.CharField(max_length=30)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Custbill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('paid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phnum', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Procbill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('paid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estname', models.CharField(max_length=30)),
                ('esttype', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=30)),
                ('phnum', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopctl.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('price', models.FloatField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopctl.batch')),
                ('custbill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopctl.custbill')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField()),
                ('price', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopctl.category')),
                ('procbill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopctl.procbill')),
            ],
        ),
        migrations.AddField(
            model_name='procbill',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopctl.source'),
        ),
        migrations.CreateModel(
            name='Pricelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedon', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopctl.batch')),
            ],
        ),
        migrations.AddField(
            model_name='custbill',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopctl.customer'),
        ),
        migrations.AddField(
            model_name='batch',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopctl.purchase'),
        ),
    ]
